project_id = "onzio-platform-contracts"

[api]
enabled = true
port = 54321
schemas = ["public", "onzio", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://alpha.localhost:3000"
additional_redirect_urls = [
  "http://alpha.localhost:3000/admin/auth/callback",
  "http://bravo.localhost:3000/admin/auth/callback"
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
